spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GE95wXZop5FjozfxFSv
      secret-key: CbXtd0ebYVulxMr5N6qtqq6sUy0Lq9
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: gulimall-zouxuan

  application:
    name: gulimall-third-party

server:
  port: 30000
